<script setup lang="ts">
import { ref,onMounted,onBeforeUnmount } from 'vue'
import * as T from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { Play, Square, Boxes, ClipboardList } from 'lucide-vue-next'
import { fetchOffice,type OfficeData } from './api'
const host=ref<HTMLDivElement>(),selected=ref(0),demo=ref(false),phase=ref(''),data=ref<OfficeData|null>(null),error=ref('连接中')
const names=['产品经理','架构师','开发工程师','测试工程师','发布工程师','运维工程师'],keys=['pm','architect','dev','qa','release','sre']
const duties=['需求边界 · 验收标准','技术方案 · 接口设计','代码实现 · 功能验证','测试计划 · 质量检查','版本打包 · 部署交付','监控告警 · 故障响应']
const colors=[0x4786dd,0x42ad90,0xe1b448,0xd97885,0x9880c7,0x52a8b8]
const homes=[[-4,-2],[-4,2],[0,-2],[0,2],[4,-2],[4,2]]
const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100),people:T.Group[]=[],legs:T.Group[][]=[]
let renderer:T.WebGLRenderer,controls:OrbitControls,observer:ResizeObserver,frame=0,start=0,timer:ReturnType<typeof setTimeout>,alive=true,ring:T.Mesh
function box(parent:T.Object3D,s:number[],p:number[],c:number){const m=new T.Mesh(new T.BoxGeometry(s[0],s[1],s[2]),new T.MeshStandardMaterial({color:c,roughness:.8}));m.position.set(p[0]!,p[1]!,p[2]!);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function monitor(x:number,z:number){box(scene,[1.1,.7,.12],[x,1.5,z],0x30444e);box(scene,[.96,.55,.025],[x,1.5,z+.075],0x90d9d5);for(let i=0;i<3;i++)box(scene,[.45-i*.07,.04,.025],[x-.1,1.65-i*.13,z+.09],0x3c818b)}
function toggle(){demo.value=!demo.value;start=performance.now();phase.value='前往设计工位'}
async function load(){try{const next=await fetchOffice(null);if(alive){data.value=next;error.value='已连接工单'}}catch{if(alive)error.value='工单服务未连接'}finally{if(alive)timer=setTimeout(load,10000)}}
function pick(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(people,true)[0];if(hit){let o=hit.object;while(o.parent&&o.userData.role===undefined)o=o.parent;if(o.userData.role!==undefined)selected.value=o.userData.role}}
onMounted(()=>{
  load();renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.value!.appendChild(renderer.domElement)
  scene.background=new T.Color(0xe8eef0);camera.position.set(12,14,17);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=15;controls.maxDistance=35;controls.maxPolarAngle=1.2
  scene.add(new T.HemisphereLight(0xffffff,0x788a91,2.4));const sun=new T.DirectionalLight(0xfff5e5,3);sun.position.set(-5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10});scene.add(sun)
  box(scene,[14,.35,11],[0,-.22,0],0xd6e0e1);box(scene,[14,3.5,.18],[0,1.6,-5.4],0xf4f5f2);box(scene,[.18,3.5,11],[-6.9,1.6,0],0xdce7e5)
  for(let x=-6;x<=6;x+=2)for(let z=-4;z<=4;z+=2)box(scene,[1.96,.025,1.96],[x,-.025,z],(x+z)%4===0?0xdce5e6:0xe6eded)
  colors.forEach((color,i)=>{const [x,z]=homes[i] as [number,number];box(scene,[2.8,.035,3.3],[x,.01,z-.3],color);box(scene,[2.45,.17,1],[x,1,z-1],0xf6f7f4);for(const dx of [-1,1])box(scene,[.14,1,.65],[x+dx,.48,z-1],0x6f8790);monitor(x,z-1.2)
    if(i===0){box(scene,[.6,.035,.45],[x+.7,1.11,z-.8],0x4786dd)}
    if(i===1){box(scene,[2,1.25,.1],[x,2,z-1.7],0xe5fff0);for(let n=0;n<3;n++)box(scene,[.3,.28,.04],[x-.6+n*.6,2,z-1.63],0x42ad90)}
    if(i===2)monitor(x+.9,z-1.2)
    if(i===3)for(let n=0;n<3;n++)box(scene,[.3,.3,.3],[x-.65+n*.55,1.24,z-.8],n===1?0xdb7885:0x45ac91)
    if(i===4)for(let n=0;n<3;n++)box(scene,[.5,.5,.5],[x+1.2,.3+n*.5,z-.9],0x9983c7)
    if(i===5){box(scene,[.7,1.8,.6],[x+1.3,.9,z-1.3],0x344650);for(let n=0;n<4;n++)box(scene,[.45,.08,.03],[x+1.3,.4+n*.3,z-.985],0x64dac0)}
    const p=new T.Group();p.userData.role=i;p.position.set(x,0,z);people.push(p);scene.add(p);box(p,[.6,.65,.36],[0,.98,0],color);box(p,[.54,.54,.49],[0,1.58,0],0xe6b698);box(p,[.58,.17,.52],[0,1.87,-.02],i===1?0xa3abad:0x35424b);for(const dx of [-.13,.13])box(p,[.06,.075,.03],[dx,1.6,.25],0x273039);for(const dx of [-.4,.4])box(p,[.2,.57,.25],[dx,.97,0],color)
    const pair:T.Group[]=[];for(const dx of [-.17,.17]){const l=new T.Group();l.position.set(dx,.65,0);box(l,[.23,.52,.25],[0,-.25,0],0x405360);box(l,[.26,.14,.4],[0,-.51,.06],0x28383f);p.add(l);pair.push(l)}legs.push(pair)
  })
  for(const x of [-6,6]){box(scene,[.65,.6,.65],[x,.3,-4.5],0x6d8990);box(scene,[.16,1.2,.16],[x,1,-4.5],0x608b71);box(scene,[1,.65,.8],[x,1.7,-4.5],0x6ba68a)}
  ring=new T.Mesh(new T.RingGeometry(.5,.62,32),new T.MeshBasicMaterial({color:0x267c99,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;scene.add(ring)
  observer=new ResizeObserver(()=>{const w=host.value!.clientWidth,h=host.value!.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(12,14,17).multiplyScalar(w/h<.85?1.4:1);camera.updateProjectionMatrix()});observer.observe(host.value!);renderer.domElement.addEventListener('pointerup',pick)
  const animate=(now:number)=>{frame=requestAnimationFrame(animate);people.forEach((p,i)=>{p.position.set(homes[i]![0]!,0,homes[i]![1]!);p.rotation.y=0;legs[i]!.forEach(l=>l.rotation.x=0)})
    if(demo.value){const t=(now-start)/1000,k=t<4?t/4:t<9?1:Math.max(0,1-(t-9)/4);people[0]!.position.lerp(new T.Vector3(-2.7,0,2),k);people[0]!.rotation.y=t<9?.4:Math.PI;if(t<4||(t>=9&&t<13))legs[0]!.forEach((l,j)=>l.rotation.x=Math.sin(now*.012+j*Math.PI)*.5);if(t>=4&&t<9)people[1]!.rotation.y=1.2;phase.value=t<4?'PM 前往设计工位':t<9?'PM 与架构师：确认需求边界':t<13?'沟通结束，返回工位':'演示完成'}
    ring.position.copy(people[selected.value]!.position);ring.position.y=.08;controls.update();renderer.render(scene,camera)
  };frame=requestAnimationFrame(animate)
})
onBeforeUnmount(()=>{alive=false;clearTimeout(timer);cancelAnimationFrame(frame);observer?.disconnect();controls?.dispose();renderer?.domElement.removeEventListener('pointerup',pick);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer?.dispose()})
</script>
<template><div class="shell"><nav><Boxes :size="28"/><a href="http://127.0.0.1:8321/" title="AI Factory 总览" target="_blank" rel="noopener"><b>AI<br>FACTORY</b></a><span>办公室</span><a href="http://127.0.0.1:8321/tickets" title="工单看板" target="_blank" rel="noopener"><ClipboardList/></a></nav><main><header><div><small>WORKSPACE / SANDBOX</small><h1>协作办公室 <em>方块人沙盒</em></h1></div><small>{{error}}</small></header><div class="metrics"><span>进行中 <b>{{data?.kpi.running ?? '—'}}</b></span><span>待审批 <b>{{data?.kpi.pending_approval ?? '—'}}</b></span><span>今日完成 <b>{{data?.kpi.today_done ?? '—'}}</b></span></div><div class="workspace"><section class="stage"><div class="toolbar"><span>研发工作区</span><button @click="toggle"><Square v-if="demo" :size="14"/><Play v-else :size="14"/>{{demo?'结束演示':'演示 PM → 架构师'}}</button></div><div class="scene"><div ref="host" class="canvas"/><div v-if="demo" class="demo"><b>演示模式</b>{{phase}}</div></div><footer>需求 / 设计 <span>→</span> 实现 / 验证 <span>→</span> 交付 / 运行</footer></section><aside><small>TEAM / 06</small><h2>协作成员</h2><button v-for="(name,i) in names" :key="name" class="member" :class="{selected:selected===i}" @click="selected=i"><i :style="{background:'#'+colors[i]!.toString(16)}"/><span>{{name}}<small>{{data?.roles.find(r=>r.key===keys[i])?.count ?? '—'}} 个阶段工单</small></span></button><div class="detail"><small>当前选中</small><h2>{{names[selected]}}</h2><p>{{duties[selected]}}</p><a v-for="t in data?.roles.find(r=>r.key===keys[selected])?.tickets || []" :key="t.id" :href="'/ticket/'+t.id">{{t.id}}<p>{{t.summary}}</p></a><p v-if="!data">{{error}}</p><p v-else-if="!data.roles.find(r=>r.key===keys[selected])?.tickets.length">暂无阶段工单</p></div></aside></div></main></div></template>
<style scoped>
.shell{display:flex;min-height:100vh;background:#f4f7f7;color:#2c424a}nav{width:78px;flex-shrink:0;display:flex;align-items:center;flex-direction:column;gap:26px;padding:25px 5px;background:white;border-right:1px solid #dce5e7;color:#347b82}nav b{text-align:center;font-size:11px}nav span{font-size:11px;padding:12px 5px;background:#e0efec}nav a{color:#68818a}main{flex:1;min-width:0;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:12px}small{font-size:11px;color:#73888d}h1{font-size:23px;margin:5px 0 20px}em{font-size:12px;font-style:normal;font-weight:400;color:#59867d;margin-left:10px}h2{font-size:17px;margin:8px 0 16px}.metrics{display:flex;gap:35px;border-top:1px solid #dce5e7;padding:18px 0;color:#70858d;font-size:12px}.metrics b{font-size:21px;margin-left:10px;color:#2c424a}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:24px}.toolbar{display:flex;align-items:center;justify-content:space-between;padding:12px 0;font-size:12px}button{font:inherit;cursor:pointer}button:focus-visible,a:focus-visible{outline:3px solid #4592aa;outline-offset:2px}.toolbar button{display:flex;align-items:center;gap:8px;border:1px solid #cbdcdd;background:white;border-radius:5px;padding:9px 12px;color:#3d696f}.scene{height: min(70vh,780px);position:relative}.canvas{height:100%;width:100%;min-height:360px}.canvas :deep(canvas){display:block;touch-action:none}.demo{position:absolute;bottom:15px;left:15px;right:15px;background:#fffef1;border:1px solid #e2d39a;padding:12px;font-size:12px;pointer-events:none}.demo b{margin-right:12px;color:#9b7b2f}footer{display:flex;justify-content:center;gap:16px;font-size:12px;color:#69828a;padding:18px}aside{border-left:1px solid #dce5e7;padding:16px 0 0 20px}.member{display:flex;align-items:center;gap:12px;width:100%;text-align:left;border:0;border-bottom:1px solid #dfe7e7;background:transparent;padding:13px 8px;color:#334d56;font-size:13px}.member.selected{background:#e0eeeb}.member small{display:block;margin-top:4px}.member i{width:14px;height:22px}.detail{padding:24px 8px}.detail p{font-size:12px;color:#72868b}.detail a{display:block;font-size:12px;color:#347c89;text-decoration:none;overflow-wrap:anywhere;border-bottom:1px solid #dfe7e7}@media(max-width:1000px){.workspace{grid-template-columns:1fr}.scene{height:60vh}aside{border:0;padding:16px 0;display:grid;grid-template-columns:1fr 1fr;gap:8px}aside>small,aside>h2,.detail{grid-column:1/-1}}@media(max-width:600px){nav{width:48px}nav b{font-size:9px}main{padding:15px 10px}h1{font-size:18px}em{display:block;margin:5px 0}.metrics{gap:12px}.metrics b{font-size:17px;margin-left:5px}.scene{height:430px}.toolbar button{font-size:11px}footer{font-size:10px;gap:8px}}
</style>
